spring:
  application:
    name: resource-service

  datasource:
    url: jdbc:postgresql://localhost:5433/resource_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

services:
  config:
    song-service-client:
      base-url: http://localhost:8081
      urls:
        post-metadata: /songs
        delete-metadata: /songs